name: BetterMinecraftCore
version: ${project.version}
main: fr.rsman.betterMinecraftCore.BetterMinecraftCore
api-version: 1.16
authors: [ RsMan ]
description: test

softdepend: [PlaceholderAPI, ItemsAdder, MythicMobs]