name: BetterMinecraftCore
version: ${project.version}
main: me.rsman.BetterMinecraftCore.BetterMinecraftCore
api-version: 1.16
authors: [ RsMan ]
description: test

softdepend: [PlaceholderAPI, ItemsAdder, MythicMobs]